name: todo_nodejs
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  get: ^4.6.6
  dio:

  # UI & Animation
  google_fonts: ^6.1.0
  flutter_animate: ^4.5.0
  flutter_slidable: ^3.0.1
  rive:
  connectivity_plus:

#  Notification
  firebase_core:
  firebase_messaging:
  cloud_firestore:

  # Utility
  intl: ^0.19.0

  # Icons
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/timeline.png"

flutter:
  uses-material-design: true
  assets:
    - assets/rive/
    - assets/images/timeline.png