// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWss9St9bce22zaYtibzhxRZXQVbJab-4',
    appId: '1:812561576577:web:634caa0b80952c016f5380',
    messagingSenderId: '812561576577',
    projectId: 'todo-node-a0f3d',
    authDomain: 'todo-node-a0f3d.firebaseapp.com',
    storageBucket: 'todo-node-a0f3d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMDu2qaxYs5CGcKdLwlAQgZIBU6NAipeY',
    appId: '1:812561576577:android:0d34028e90ab6aba6f5380',
    messagingSenderId: '812561576577',
    projectId: 'todo-node-a0f3d',
    storageBucket: 'todo-node-a0f3d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwAaknht23j6kqqKP87t5cSbW6xHnDW7g',
    appId: '1:812561576577:ios:859151af65771c516f5380',
    messagingSenderId: '812561576577',
    projectId: 'todo-node-a0f3d',
    storageBucket: 'todo-node-a0f3d.firebasestorage.app',
    iosBundleId: 'com.example.todoNodejs',
  );
}
